import {
  addMovie,
  addPopularMovies,
  addTopratedMovies,
  addUpcomingMovies,
  addAdultMovies,       
  addActionMovies,
  addAdventureMovies,
  addAnimationMovies,
  addComedyMovies,
  addCrimeMovies,
  addDocumentaryMovies,
  addDramaMovies,
  addFamilyMovies,
  addFantasyMovies,
  addHistoryMovies,
  addHorrorMovies,
  addMusicMovies,
  addMysteryMovies,
  addRomanceMovies,
  addScifiMovies,
  addTvMovies,
  addThrillerMovies,
  addWarMovies,
  addWesternMovies,
} from "./redux/MovieSlice";

const actionMap = {
  addMovie,
  addPopularMovies,
  addTopratedMovies,
  addUpcomingMovies,
  addAdultMovies,       
  addActionMovies,
  addAdventureMovies,
  addAnimationMovies,
  addComedyMovies,
  addCrimeMovies,
  addDocumentaryMovies,
  addDramaMovies,
  addFamilyMovies,
  addFantasyMovies,
  addHistoryMovies,
  addHorrorMovies,
  addMusicMovies,
  addMysteryMovies,
  addRomanceMovies,
  addScifiMovies,
  addTvMovies,
  addThrillerMovies,
  addWarMovies,
  addWesternMovies,
};

export default actionMap;
