import {
  addMovie,
  addPopularMovies,
  addTopratedMovies,
  addUpcomingMovies,
  addAdultMovies,
  addActionMovies,
  addAdventureMovies,
  addAnimationMovies,
  addComedyMovies,
  addCrimeMovies,
  addDocumentaryMovies,
  addDramaMovies,
  addFamilyMovies,
  addFantasyMovies,
  addHistoryMovies,
  addHorrorMovies,
  addMusicMovies,
  addMysteryMovies,
  addRomanceMovies,
  addScifiMovies,
  addTvMovies,
  addThrillerMovies,
  addWarMovies,
  addWesternMovies,
} from "./redux/MovieSlice";

import {
  addAiringToday,
  addOnTheAir,
  addPopularTv,
  addTopRatedTv,
  addAdultTv,
  addActionTv,
  addAnimationTv,
  addComedyTv,
  addCrimeTv,
  addDocumentaryTv,
  addDramaTv,
  addFamilyTv,
  addKidsTv,
  addMysteryTv,
  addNewsTv,
  addRealityTv,
  addScifiFantasyTv,
  addSoapTv,
  addTalkTv,
  addWarPoliticsTv,
  addWesternTv,
} from "./redux/tvSlice";

const actionMap = {
  // Movie actions
  addMovie,
  addPopularMovies,
  addTopratedMovies,
  addUpcomingMovies,
  addAdultMovies,
  addActionMovies,
  addAdventureMovies,
  addAnimationMovies,
  addComedyMovies,
  addCrimeMovies,
  addDocumentaryMovies,
  addDramaMovies,
  addFamilyMovies,
  addFantasyMovies,
  addHistoryMovies,
  addHorrorMovies,
  addMusicMovies,
  addMysteryMovies,
  addRomanceMovies,
  addScifiMovies,
  addTvMovies,
  addThrillerMovies,
  addWarMovies,
  addWesternMovies,

  // TV actions
  addAiringToday,
  addOnTheAir,
  addPopularTv,
  addTopRatedTv,
  addAdultTv,
  addActionTv,
  addAnimationTv,
  addComedyTv,
  addCrimeTv,
  addDocumentaryTv,
  addDramaTv,
  addFamilyTv,
  addKidsTv,
  addMysteryTv,
  addNewsTv,
  addRealityTv,
  addScifiFantasyTv,
  addSoapTv,
  addTalkTv,
  addWarPoliticsTv,
  addWesternTv,
};

export default actionMap;
